# Generated by repro: do not edit by hand
# Please edit Dockerfiles in .repro/
FROM rocker/verse:4.1.2
WORKDIR /home/rstudio
RUN apt-get update -y && apt-get install -y rsync
RUN tlmgr install collection-latexrecommended
RUN install2.r --error --skipinstalled \ 
  DataExplorer \ 
  echarts4r \ 
  ggplot2 \ 
  janitor \ 
  skimr \ 
  tidyverse \ 
  viridis
RUN installGithub.r \ 
  aaronpeikert/repro@adb5fa569
